import Ivan from '../../../assets/user/avatarIvan.svg';
import Mikhael from '../../../assets/EventsMessagesBlock/Michael.svg';
import Liza from '../../../assets/EventsMessagesBlock/Liza.svg';
import { INotificationProps } from '../../../store/notifications/types';

export const notifications: INotificationProps[] = [
  {
    id: '0',
    image: Ivan,
    type: 'new',
    name: 'Ivan',
    time: '2021-11-01T11:00:00Z',
    event: 'Movie night',
    premium: true,
    status: 'online',
  },
  {
    id: '1',
    image: Mikhael,
    type: 'like',
    name: 'Mikhael',
    time: '2021-11-01T12:15:23Z',
    event: 'Coffee date',
    premium: false,
    status: 'online',
  },
  {
    id: '2',
    image: Liza,
    type: 'event',
    name: 'Liza',
    time: '2021-10-29T10:00:00Z',
    event: 'Dinner',
    premium: false,
    status: 'offline',
  },
  {
    id: '3',
    image: Ivan,
    name: 'Ivan',
    type: 'decline',
    time: '2021-10-25T18:00:00Z',
    event: 'Lunch',
    premium: false,
    status: 'online',
  },
  {
    id: '4',
    image: Liza,
    name: 'Liza',
    type: 'accept',
    time: '2021-10-25T12:00:00Z',
    event: 'Movie night',
    premium: false,
    status: 'offline',
  },
  {
    id: '5',
    image: Ivan,
    type: 'new',
    name: 'Ivan',
    time: '2021-11-01T11:00:00Z',
    event: 'Movie night',
    premium: true,
    status: 'online',
  },
  {
    id: '6',
    image: Mikhael,
    type: 'like',
    name: 'Mikhael',
    time: '2021-11-01T12:15:23Z',
    event: 'Coffee date',
    premium: false,
    status: 'online',
  },
  {
    id: '7',
    image: Liza,
    type: 'event',
    name: 'Liza',
    time: '2021-10-29T10:00:00Z',
    event: 'Dinner',
    premium: false,
    status: 'offline',
  },
  {
    id: '8',
    image: Ivan,
    name: 'Ivan',
    type: 'decline',
    time: '2021-10-25T18:00:00Z',
    event: 'Lunch',
    premium: false,
    status: 'online',
  },
  {
    id: '9',
    image: Liza,
    name: 'Liza',
    type: 'accept',
    time: '2021-10-25T12:00:00Z',
    event: 'Movie night',
    premium: false,
    status: 'offline',
  },
  {
    id: '10',
    image: Ivan,
    type: 'new',
    name: 'Ivan',
    time: '2021-11-01T11:00:00Z',
    event: 'Movie night',
    premium: true,
    status: 'online',
  },
  {
    id: '11',
    image: Mikhael,
    type: 'like',
    name: 'Mikhael',
    time: '2021-11-01T12:15:23Z',
    event: 'Coffee date',
    premium: false,
    status: 'online',
  },
];
